# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

In [23]:
import os 

print("Current working directory:", os.getcwd())
print("\nFiles and folders:")
print(os.listdir())

Current working directory: c:\Users\HP\Documents\moringa_datascience\dsc-course0-m8-lab-main\dsc-course0-m8-lab-main

Files and folders:
['Aviation_Accidents_Cleaning.ipynb', 'Aviation_Accidents_Data_Analysis.ipynb', 'data', 'LICENSE', 'README.md']

In [24]:
import os

print(os.listdir("data"))

['.gitkeep', 'AviationData.csv', 'USState_Codes.csv']

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [25]:
df = pd.read_csv("data/AviationData.csv", encoding="latin1,", low_memory=False)

df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [26]:
#Inspect the dataframe
# Check the number of rows and columns
print("Dataset shape:", df.shape)

# Inspect the column names
print("\column names:")
print(df.columns.tolist())


print("\nData types and non-null values:")
df.info()

Dataset shape: (88889, 31)
\column names:
['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date']

Data types and non-null values:
<class 'pandas.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  str
 1   Investigation.Type      88889 non-null  str
 2   Accident.Number         88889 non-null  str
 3   Event.Date              88889 non-null  str
 4   Location                88837 non-null  str
 5   Country                 88663 non-null  str
 6   Latitude                34382 non-null  str
 7   Longitude               34373 non-null  str
 8   Airport.Code            50132 non-null  str
 9   Airport.Name            52704 non-null  str
 10  Injury.Severity         87889 non-null  str
 11  Aircraft.damage         85695 non-null  str
 12  Aircraft.Category       32287 non-null  str
 13  Registration.Number     87507 non-null  str
 14  Make                    88826 non-null  str
 15  Model                   88797 non-null  str
 16  Amateur.Built           88787 non-null  str
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  str
 19  FAR.Description         32023 non-null  str
 20  Schedule                12582 non-null  str
 21  Purpose.of.flight       82697 non-null  str
 22  Air.carrier             16648 non-null  str
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  str
 28  Broad.phase.of.flight   61724 non-null  str
 29  Report.Status           82505 non-null  str
 30  Publication.Date        75118 non-null  str
dtypes: float64(5), str(26)
memory usage: 39.5 MB

In [27]:
# Count missing values in each column
print("Missing values per column:")
print(df.isnull().sum())

#Calculate the percentage of missing values
print("\npercentage of missing values:")
print((df.isnull().mean() * 100).round(2))

#Summary statistics for all columns
print("\nSummary statistics:")
df.describe(include="all")

Missing values per column:
Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

percentage of missing values:
Event.Id                   0.00
Investigation.Type         0.00
Accident.Number            0.00
Event.Date                 0.00
Location                   0.06
Country                    0.25
Latitude                  61.32
Longitude                 61.33
Airport.Code              43.60
Airport.Name              40.71
Injury.Severity            1.12
Aircraft.damage            3.59
Aircraft.Category         63.68
Registration.Number        1.55
Make                       0.07
Model                      0.10
Amateur.Built              0.11
Number.of.Engines          6.84
Engine.Type                7.98
FAR.Description           63.97
Schedule                  85.85
Purpose.of.flight          6.97
Air.carrier               81.27
Total.Fatal.Injuries      12.83
Total.Serious.Injuries    14.07
Total.Minor.Injuries      13.42
Total.Uninjured            6.65
Weather.Condition          5.05
Broad.phase.of.flight     30.56
Report.Status              7.18
Publication.Date          15.49
dtype: float64

Summary statistics:

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
count,88889,88889,88889,88889,88837,88663,34382,34373,50132,52704,...,82697,16648,77488.000000,76379.000000,76956.000000,82977.000000,84397,61724,82505,75118
unique,87951,2,88863,14782,27758,219,25589,27154,10374,24870,...,26,13590,NaN,NaN,NaN,NaN,4,12,17074,2924
top,20001214X45071,Accident,ERA22LA103,1982-05-16,"ANCHORAGE, AK",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,NaN,NaN,NaN,NaN,VMC,Landing,Probable Cause,25-09-2020
freq,3,85015,2,25,434,82248,19,24,1488,240,...,49448,258,NaN,NaN,NaN,NaN,77303,15428,61754,17019
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.647855,0.279881,0.357061,5.325440,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.485960,1.544084,2.235625,27.913634,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,349.000000,161.000000,380.000000,699.000000,NaN,NaN,NaN,NaN

In [28]:
print("Investigation types:")
print(df["Investigation.Type"].value_counts(dropna=False))

print("\nAircraft damage:")
print(df["Aircraft.damage"].value_counts(dropna=False))

print("\nAircraft makes:")
print(df["Make"].value_counts().head(20))

print("\nAircraft categories:")
print(df["Aircraft.Category"].value_counts(dropna=False))

Investigation types:
Investigation.Type
Accident    85015
Incident     3874
Name: count, dtype: int64

Aircraft damage:
Aircraft.damage
Substantial    64148
Destroyed      18623
NaN             3194
Minor           2805
Unknown          119
Name: count, dtype: int64

Aircraft makes:
Make
Cessna               22227
Piper                12029
CESSNA                4922
Beech                 4330
PIPER                 2841
Bell                  2134
Boeing                1594
BOEING                1151
Grumman               1094
Mooney                1092
BEECH                 1042
Robinson               946
Bellanca               886
Hughes                 795
Schweizer              629
Air Tractor            595
BELL                   588
Mcdonnell Douglas      526
Aeronca                487
Maule                  445
Name: count, dtype: int64

Aircraft categories:
Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

## Data Cleaning

### Filtering aircrafts and events

### DATA CLEANING AND FILTERING AIRCRAFTS AND EVENTS
The dataset contains several data quality issues that need to be addressed before analysis.
1. Filtering accident records: The dataset includes both accidents and incidents. Only accident records will be retained to focus the analysis on aircraft safety.
2. Aircraft damage: The Aircraft.damage column contains missing and unknown values that need to be reviewed before calculating aircraftdestruction rates.
3. Aircraft manufacturer names: Inconsistent capitalisation such as Cessna and CESSNA, will be standadized to ensure consistent grouping and accurate manufacturer counts.
4. Missing values: Missing data in key columns will be examined and handled using appropriate methods to maintain the relianility of the analysis.
5. Aircraft categories: The Aircraft.Category column contains a high number of missing values.

In [29]:
df = df[df["Investigation.Type"] == "Accident"].copy()

df["Make"] = df["Make"].str.strip().str.upper()

print("Dataset shape after filtering:", df.shape)
print(df["Make"].value_counts().head(20))

Dataset shape after filtering: (85015, 31)
Make
CESSNA            26793
PIPER             14684
BEECH              5177
BELL               2662
BOEING             1362
MOONEY             1311
ROBINSON           1219
GRUMMAN            1158
BELLANCA           1040
HUGHES              925
SCHWEIZER           770
AIR TRACTOR         689
AERONCA             633
MAULE               587
CHAMPION            517
STINSON             436
AERO COMMANDER      422
LUSCOMBE            414
TAYLORCRAFT         383
NORTH AMERICAN      377
Name: count, dtype: int64

In [30]:
#Check missing and unknown aircraft damage values
print("Missing aircraft damage values:", df["Aircraft.damage"].isna().sum())
print("\nAircraft damage categories:")
print(df["Aircraft.damage"].value_counts(dropna=False))

#Check missing aircraft categories
print("\nMissing aircraft categories:", df["Aircraft.Category"].isna().sum())
print("\nAircraft categories:")
print(df["Aircraft.Category"].value_counts(dropna=False))

#Check the dataset after cleaning
print("\nDataset shape after filtering:", df.shape)
print("\nTop 20 aircraft manufacturers:")
print(df["Make"].value_counts().head(20))

Missing aircraft damage values: 1460

Aircraft damage categories:
Aircraft.damage
Substantial    64106
Destroyed      18615
NaN             1460
Minor            737
Unknown           97
Name: count, dtype: int64

Missing aircraft categories: 54480

Aircraft categories:
Aircraft.Category
NaN                  54480
Airplane             25963
Helicopter            3348
Glider                 508
Balloon                229
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 12
WSFT                     9
Blimp                    4
Powered-Lift             3
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

Dataset shape after filtering: (85015, 31)

Top 20 aircraft manufacturers:
Make
CESSNA            26793
PIPER             14684
BEECH              5177
BELL               2662
BOEING             1362
MOONEY             1311
ROBINSON           1219
GRUMMAN            1158
BELLANCA           1040
HUGHES              925
SCHWEIZER           770
AIR TRACTOR         689
AERONCA             633
MAULE               587
CHAMPION            517
STINSON             436
AERO COMMANDER      422
LUSCOMBE            414
TAYLORCRAFT         383
NORTH AMERICAN      377
Name: count, dtype: int64

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [32]:
columns_to_check = [
    "Investigation.Type",
    "Make",
    "Model",
    "Aircraft.Category",
    "Aircraft.damage",
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured",
]

print(df[columns_to_check].head())

print("\nMissing values:")
print(df[columns_to_check].isnull().sum())

  Investigation.Type      Make     Model Aircraft.Category Aircraft.damage  \
0           Accident   STINSON     108-3               NaN       Destroyed
1           Accident     PIPER  PA24-180               NaN       Destroyed
2           Accident    CESSNA      172M               NaN       Destroyed
3           Accident  ROCKWELL       112               NaN       Destroyed
4           Accident    CESSNA       501               NaN       Destroyed

   Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  \
0                   2.0                     0.0                   0.0
1                   4.0                     0.0                   0.0
2                   3.0                     NaN                   NaN
3                   2.0                     0.0                   0.0
4                   1.0                     2.0                   NaN

   Total.Uninjured
0              0.0
1              0.0
2              NaN
3              0.0
4              0.0

Missing values:
Investigation.Type            0
Make                         36
Model                        60
Aircraft.Category         54480
Aircraft.damage            1460
Total.Fatal.Injuries      10756
Total.Serious.Injuries    11863
Total.Minor.Injuries      11309
Total.Uninjured            5768
dtype: int64

In [34]:
#Remove records with missing aircraft make or model
df = df.dropna(subset=["Make", "Model"]).copy()

#Check the dataset after filtering
print("Dataset shape after filtering:", df.shape)

print("\nMissing values in make:", df["Make"].isnull().sum())
print("Missing values in Model:", df["Model"].isnull().sum())

Dataset shape after filtering: (84937, 31)

Missing values in make: 0
Missing values in Model: 0

### Filtering Aircraft Records

The dataset was filtered to remove records with missing aircraft manufacturer (Make) or model (Model) information. This ensures that each remaining record can be associated with a known aircraft manufacturer and model, allowing for more reliable comparisons of aircraft safety. After filtering, the dataset contained 84,937 rows and 31 columns, with no missing values in the Make or Model columns.

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [37]:
# Estimate the total number of people on each flight
injury_columns = [
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured",
]

# Fill missing injury counts with zero for this initial estimate
df[injury_columns] = df[injury_columns].fillna(0)

#Calculate the estimated total number of people on each flight
df["Total.People"] = df[injury_columns].sum(axis=1)

# Display the results
print(df[injury_columns + ["Total.People"]].head())

   Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  \
0                   2.0                     0.0                   0.0
1                   4.0                     0.0                   0.0
2                   3.0                     0.0                   0.0
3                   2.0                     0.0                   0.0
4                   1.0                     2.0                   0.0

   Total.Uninjured  Total.People
0              0.0           2.0
1              0.0           4.0
2              0.0           3.0
3              0.0           2.0
4              0.0           3.0

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [41]:
#Inspect aircraft damage categories and missing values
print("Aircraft damage categories:")
print(df["Aircraft.damage"].value_counts(dropna=False))

print("\nMissing values:")
print(df["Aircraft.damage"].isnull().sum())

Aircraft damage categories:
Aircraft.damage
Substantial    64055
Destroyed      18589
NaN             1459
Minor            737
Unknown           97
Name: count, dtype: int64

Missing values:
1459

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [42]:
#Remove records with missing aircraft manufactured names
df = df.dropna(subset=["Make"]).copy()

#Standardize manufacturer names
df["Make"] = df["Make"].str.strip().str.upper()

#Count acciedent records for each manufacturer
make_counts = df["Make"].value_counts()

#Keep manufacturers with at least 50 accident records
valid_makes = make_counts[make_counts >= 50].index
df = df[df["Make"].isin(valid_makes)].copy()

#Verify the cleaned dataset
print("Dataset shape:", df.shape)
print("Number of manufacturers:", df["Make"].nunique())
print("\nManufacturer counts:")
print(df["Make"].value_counts().head(20))

Dataset shape: (70852, 32)
Number of manufacturers: 91

Manufacturer counts:
Make
CESSNA            26789
PIPER             14683
BEECH              5176
BELL               2662
BOEING             1359
MOONEY             1311
ROBINSON           1218
GRUMMAN            1158
BELLANCA           1040
HUGHES              925
SCHWEIZER           770
AIR TRACTOR         689
AERONCA             633
MAULE               587
CHAMPION            517
STINSON             436
AERO COMMANDER      422
LUSCOMBE            414
TAYLORCRAFT         383
NORTH AMERICAN      377
Name: count, dtype: int64

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [44]:
# Remove records with missing model names
df = df.dropna(subset=["Model"]).copy()

#Clean and standardize model names
df["Model"] = df["Model"].str.strip().str.upper()

#Check missing values values and dataset size
print("Missing Model values:", df["Model"].isnull().sum())
print("Dataset shape:", df.shape)

#Inspect the most common models
print("\nTop 20 aircraft models:")
print(df["Model"].value_counts().head(20))

#Check whether model names are shared across manufacturers
model_make_counts = df.groupby("Model")["Make"].nunique()

shared_models = model_make_counts[model_make_counts > 1]

print("\nNumber of model names shared by multiple manufacturers:")
print(len(shared_models))

print("\nExamples of shared moedl names:")
print(shared_models.head(20))

# Create a unique identifier for each aircraft type
df["Plane.Type"] = (
    df["Make"].str.strip().str.upper()
    + "_"
    +df["Model"]
)

#Display and verify
print("\nAircraft type examples:")
print(df[["Make", "Model", "Plane.Type"]].head(10))

print("\nNumber of unique aircraft types:", df["Plane.Type"].nunique())

Missing Model values: 0
Dataset shape: (70852, 33)

Top 20 aircraft models:
Model
152          2348
172          1744
172N         1160
PA-28-140     929
150           822
172M          793
172P          685
182           653
180           621
150M          583
PA-18         578
PA-28-180     571
PA-18-150     571
PA-28-161     561
PA-28-181     525
206B          515
PA-38-112     464
150L          458
G-164A        453
A36           435
Name: count, dtype: int64

Number of model names shared by multiple manufacturers:
418

Examples of shared moedl names:
Model
100        3
100-180    2
105        2
109        2
109A       2
112        5
112A       3
112TC      3
112TCA     3
114        2
114A       2
12         2
120        2
140        2
162        2
164        2
164B       2
170        2
18         3
180        2
Name: Make, dtype: int64

Aircraft type examples:
                Make         Model                   Plane.Type
0            STINSON         108-3                STINSON_108-3
1              PIPER      PA24-180               PIPER_PA24-180
2             CESSNA          172M                  CESSNA_172M
3           ROCKWELL           112                 ROCKWELL_112
4             CESSNA           501                   CESSNA_501
5  MCDONNELL DOUGLAS           DC9        MCDONNELL DOUGLAS_DC9
6             CESSNA           180                   CESSNA_180
7             CESSNA           140                   CESSNA_140
8             CESSNA          401B                  CESSNA_401B
9     NORTH AMERICAN  NAVION L-17B  NORTH AMERICAN_NAVION L-17B

Number of unique aircraft types: 6320

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [50]:
# Columns to inspect an clean
columns_to_clean = [
    "Engine.Type",
    "Weather.Condition",
    "Number.of.Engines",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

# Inspect the original values and missing values
for column in columns_to_clean:
    print(f"\n--- {column} ---")
    print("Missing values:", df[column].isnull().sum())
    print(df[column].value_counts(dropna=False).head(20))

#Clean text columns by removing extra spaces and standadizing capitalisation
text_columns = [
    "Engine.Type",
    "Weather.Condition",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]    


for column in text_columns:
    df[column] = df[column].apply(
        lambda value: value.strip().upper()
        if isinstance(value, str) else value
    )

#Clean Number.of.Engines by converting it to Numeric
df["Number.of.Engines"] = pd.to_numeric(
    df["Number.of.Engines"], errors="coerce"
)    

#Verify the cleaned values
print("\n---Verfification after cleaning---")

for column in columns_to_clean:
    print(f"\n{column}:")
    print(df[column].value_counts(dropna=False).head(15))

print("\nDataset shape:", df.shape)

--- Engine.Type ---
Missing values: 4424
Engine.Type
RECIPROCATING    57960
NaN               4424
TURBO SHAFT       3020
TURBO PROP        2509
UNKNOWN           1493
TURBO FAN         1120
TURBO JET          323
LR                   1
UNK                  1
NONE                 1
Name: count, dtype: int64

--- Weather.Condition ---
Missing values: 2562
Weather.Condition
VMC    62058
IMC     5343
NaN     2562
UNK      703
Unk      186
Name: count, dtype: int64

--- Number.of.Engines ---
Missing values: 3893
Number.of.Engines
1.0    57333
2.0     8456
NaN     3893
0.0      779
4.0      207
3.0      183
8.0        1
Name: count, dtype: int64

--- Purpose.of.flight ---
Missing values: 3663
Purpose.of.flight
Personal                     38921
Instructional                 9722
Unknown                       4885
Aerial Application            4286
NaN                           3663
Business                      3640
Positioning                   1373
Other Work Use                1049
Aerial Observation             723
Ferry                          683
Public Aircraft                647
Executive/corporate            432
Skydiving                      176
Flight Test                    153
Banner Tow                      97
External Load                   85
Public Aircraft - Federal       73
Public Aircraft - State         57
Public Aircraft - Local         50
Glider Tow                      41
Name: count, dtype: int64

--- Broad.phase.of.flight ---
Missing values: 18986
Broad.phase.of.flight
NaN            18986
Landing        13616
Takeoff        10190
Cruise          8690
Maneuvering     6666
Approach        5395
Taxi            1630
Climb           1586
Descent         1563
Go-around       1234
Standing         766
Unknown          444
Other             86
Name: count, dtype: int64

---Verfification after cleaning---

Engine.Type:
Engine.Type
RECIPROCATING    57960
NaN               4424
TURBO SHAFT       3020
TURBO PROP        2509
UNKNOWN           1493
TURBO FAN         1120
TURBO JET          323
LR                   1
UNK                  1
NONE                 1
Name: count, dtype: int64

Weather.Condition:
Weather.Condition
VMC    62058
IMC     5343
NaN     2562
UNK      889
Name: count, dtype: int64

Number.of.Engines:
Number.of.Engines
1.0    57333
2.0     8456
NaN     3893
0.0      779
4.0      207
3.0      183
8.0        1
Name: count, dtype: int64

Purpose.of.flight:
Purpose.of.flight
PERSONAL               38921
INSTRUCTIONAL           9722
UNKNOWN                 4885
AERIAL APPLICATION      4286
NaN                     3663
BUSINESS                3640
POSITIONING             1373
OTHER WORK USE          1049
AERIAL OBSERVATION       723
FERRY                    683
PUBLIC AIRCRAFT          647
EXECUTIVE/CORPORATE      432
SKYDIVING                176
FLIGHT TEST              153
BANNER TOW                97
Name: count, dtype: int64

Broad.phase.of.flight:
Broad.phase.of.flight
NaN            18986
LANDING        13616
TAKEOFF        10190
CRUISE          8690
MANEUVERING     6666
APPROACH        5395
TAXI            1630
CLIMB           1586
DESCENT         1563
GO-AROUND       1234
STANDING         766
UNKNOWN          444
OTHER             86
Name: count, dtype: int64

Dataset shape: (70852, 34)

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [52]:
#Inspect msissing values in each column 
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)

print("Percentage of missing values in each column:")
print(missing_percentage)

#Identify colmuns with more than 50% missing values
columns_to_drop = missing_percentage[missing_percentage > 50].index.tolist()

print("\nColumns selected for removal:")
print(columns_to_drop)

#Check the dataset after column removal
print("\nDataset shape after column removal:", df.shape)
print("\nRemaining columns:")
print(df.columns.tolist())

Percentage of missing values in each column:
Schedule                  87.305933
Air.carrier               83.540338
FAR.Description           67.093378
Aircraft.Category         66.932479
Longitude                 64.207080
Latitude                  64.200023
Airport.Code              43.764467
Airport.Name              40.598713
Broad.phase.of.flight     26.796703
Publication.Date          16.394738
Engine.Type                6.244002
Report.Status              5.805058
Number.of.Engines          5.494552
Purpose.of.flight          5.169932
Weather.Condition          3.615988
Aircraft.damage            1.671089
Registration.Number        1.332355
Injury.Severity            0.382487
Country                    0.265342
Amateur.Built              0.067747
Location                   0.053633
Event.Id                   0.000000
Investigation.Type         0.000000
Model                      0.000000
Accident.Number            0.000000
Event.Date                 0.000000
Make                       0.000000
Total.Minor.Injuries       0.000000
Total.Fatal.Injuries       0.000000
Total.Serious.Injuries     0.000000
Total.Uninjured            0.000000
Total.People               0.000000
Plan.Type                  0.000000
Plane.Type                 0.000000
dtype: float64

Columns selected for removal:
['Schedule', 'Air.carrier', 'FAR.Description', 'Aircraft.Category', 'Longitude', 'Latitude']

Dataset shape after column removal: (70852, 34)

Remaining columns:
['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date', 'Total.People', 'Plan.Type', 'Plane.Type']

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [53]:
#Save the cleaned dataset to a csv file
df.to_csv("data/AviationData_Cleaned.csv", index=False)

#Confirm that the dataset has been saved
print("Cleaned dataset saved successfully!")
print("Dataset shape:", df.shape)

#Display the first rows
print(df.head())

Cleaned dataset saved successfully!
Dataset shape: (70852, 34)
         Event.Id Investigation.Type Accident.Number  Event.Date  \
0  20001218X45444           Accident      SEA87LA080  1948-10-24
1  20001218X45447           Accident      LAX94LA336  1962-07-19
2  20061025X01555           Accident      NYC07LA005  1974-08-30
3  20001218X45448           Accident      LAX96LA321  1977-06-19
4  20041105X01764           Accident      CHI79FA064  1979-08-02

          Location        Country   Latitude   Longitude Airport.Code  \
0  MOOSE CREEK, ID  United States        NaN         NaN          NaN
1   BRIDGEPORT, CA  United States        NaN         NaN          NaN
2    Saltville, VA  United States  36.922223  -81.878056          NaN
3       EUREKA, CA  United States        NaN         NaN          NaN
4       Canton, OH  United States        NaN         NaN          NaN

  Airport.Name  ... Total.Serious.Injuries Total.Minor.Injuries  \
0          NaN  ...                    0.0                  0.0
1          NaN  ...                    0.0                  0.0
2          NaN  ...                    0.0                  0.0
3          NaN  ...                    0.0                  0.0
4          NaN  ...                    2.0                  0.0

  Total.Uninjured Weather.Condition Broad.phase.of.flight   Report.Status  \
0             0.0               UNK                CRUISE  Probable Cause
1             0.0               UNK               UNKNOWN  Probable Cause
2             0.0               IMC                CRUISE  Probable Cause
3             0.0               IMC                CRUISE  Probable Cause
4             0.0               VMC              APPROACH  Probable Cause

  Publication.Date  Total.People       Plan.Type      Plane.Type
0              NaN           2.0   STINSON_108-3   STINSON_108-3
1       19-09-1996           4.0  PIPER_PA24-180  PIPER_PA24-180
2       26-02-2007           3.0     CESSNA_172M     CESSNA_172M
3       12-09-2000           2.0    ROCKWELL_112    ROCKWELL_112
4       16-04-1980           3.0      CESSNA_501      CESSNA_501

[5 rows x 34 columns]